### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by QingWei-Li** [QingWei-Li/docsify#19]
- [x] hash router ~~(as a plugin)~~ #2
- [x] new theme https://github.com/egoist/hack
- [ ] ~~prev/next button~~
- [x] Improved scrolling on mobile 
- [ ] new theme yoga.css https://facebook.github.io/yoga/docs/margin-padding-border/
- [ ] more CDNs
